# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4216a956be23c75610ab0c5032739cc428d6245b6f41f05a02d4e4fb07647212adf0520ea409bb0e088ae3904e2ac8a16ecce0f600f3d7d252f4bad911e722a

test:
  secret_key_base: 98d77b06da627a590215cb032cf37d7b8a0b83294e78576eec32642c36730b2a284de0541c435aff5be4e23926ea6752d3f98219e23d8550a399b2cab138d25c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
